/**
 * Country metadata keyed by ISO 3166-1 numeric code (string).
 * Used by WorldMap to display country info on hover.
 */
export const COUNTRY_DATA = {
  '4':   { name: 'Afghanistan', capital: 'Kabul', flag: '🇦🇫' },
  '8':   { name: 'Albania', capital: 'Tirana', flag: '🇦🇱' },
  '12':  { name: 'Algeria', capital: 'Algiers', flag: '🇩🇿' },
  '24':  { name: 'Angola', capital: 'Luanda', flag: '🇦🇴' },
  '32':  { name: 'Argentina', capital: 'Buenos Aires', flag: '🇦🇷' },
  '51':  { name: 'Armenia', capital: 'Yerevan', flag: '🇦🇲' },
  '36':  { name: 'Australia', capital: 'Canberra', flag: '🇦🇺' },
  '40':  { name: 'Austria', capital: 'Vienna', flag: '🇦🇹' },
  '31':  { name: 'Azerbaijan', capital: 'Baku', flag: '🇦🇿' },
  '44':  { name: 'Bahamas', capital: 'Nassau', flag: '🇧🇸' },
  '50':  { name: 'Bangladesh', capital: 'Dhaka', flag: '🇧🇩' },
  '112': { name: 'Belarus', capital: 'Minsk', flag: '🇧🇾' },
  '56':  { name: 'Belgium', capital: 'Brussels', flag: '🇧🇪' },
  '84':  { name: 'Belize', capital: 'Belmopan', flag: '🇧🇿' },
  '204': { name: 'Benin', capital: 'Porto-Novo', flag: '🇧🇯' },
  '64':  { name: 'Bhutan', capital: 'Thimphu', flag: '🇧🇹' },
  '68':  { name: 'Bolivia', capital: 'Sucre', flag: '🇧🇴' },
  '70':  { name: 'Bosnia and Herzegovina', capital: 'Sarajevo', flag: '🇧🇦' },
  '72':  { name: 'Botswana', capital: 'Gaborone', flag: '🇧🇼' },
  '76':  { name: 'Brazil', capital: 'Brasília', flag: '🇧🇷' },
  '96':  { name: 'Brunei', capital: 'Bandar Seri Begawan', flag: '🇧🇳' },
  '100': { name: 'Bulgaria', capital: 'Sofia', flag: '🇧🇬' },
  '854': { name: 'Burkina Faso', capital: 'Ouagadougou', flag: '🇧🇫' },
  '108': { name: 'Burundi', capital: 'Gitega', flag: '🇧🇮' },
  '116': { name: 'Cambodia', capital: 'Phnom Penh', flag: '🇰🇭' },
  '120': { name: 'Cameroon', capital: 'Yaoundé', flag: '🇨🇲' },
  '124': { name: 'Canada', capital: 'Ottawa', flag: '🇨🇦' },
  '140': { name: 'Central African Republic', capital: 'Bangui', flag: '🇨🇫' },
  '148': { name: 'Chad', capital: "N'Djamena", flag: '🇹🇩' },
  '152': { name: 'Chile', capital: 'Santiago', flag: '🇨🇱' },
  '156': { name: 'China', capital: 'Beijing', flag: '🇨🇳' },
  '170': { name: 'Colombia', capital: 'Bogotá', flag: '🇨🇴' },
  '178': { name: 'Congo', capital: 'Brazzaville', flag: '🇨🇬' },
  '180': { name: 'DR Congo', capital: 'Kinshasa', flag: '🇨🇩' },
  '188': { name: 'Costa Rica', capital: 'San José', flag: '🇨🇷' },
  '384': { name: "Côte d'Ivoire", capital: 'Yamoussoukro', flag: '🇨🇮' },
  '191': { name: 'Croatia', capital: 'Zagreb', flag: '🇭🇷' },
  '192': { name: 'Cuba', capital: 'Havana', flag: '🇨🇺' },
  '196': { name: 'Cyprus', capital: 'Nicosia', flag: '🇨🇾' },
  '203': { name: 'Czechia', capital: 'Prague', flag: '🇨🇿' },
  '208': { name: 'Denmark', capital: 'Copenhagen', flag: '🇩🇰' },
  '262': { name: 'Djibouti', capital: 'Djibouti', flag: '🇩🇯' },
  '214': { name: 'Dominican Republic', capital: 'Santo Domingo', flag: '🇩🇴' },
  '218': { name: 'Ecuador', capital: 'Quito', flag: '🇪🇨' },
  '818': { name: 'Egypt', capital: 'Cairo', flag: '🇪🇬' },
  '222': { name: 'El Salvador', capital: 'San Salvador', flag: '🇸🇻' },
  '226': { name: 'Equatorial Guinea', capital: 'Malabo', flag: '🇬🇶' },
  '232': { name: 'Eritrea', capital: 'Asmara', flag: '🇪🇷' },
  '233': { name: 'Estonia', capital: 'Tallinn', flag: '🇪🇪' },
  '231': { name: 'Ethiopia', capital: 'Addis Ababa', flag: '🇪🇹' },
  '238': { name: 'Falkland Islands', capital: 'Stanley', flag: '🇫🇰' },
  '242': { name: 'Fiji', capital: 'Suva', flag: '🇫🇯' },
  '246': { name: 'Finland', capital: 'Helsinki', flag: '🇫🇮' },
  '250': { name: 'France', capital: 'Paris', flag: '🇫🇷' },
  '266': { name: 'Gabon', capital: 'Libreville', flag: '🇬🇦' },
  '270': { name: 'Gambia', capital: 'Banjul', flag: '🇬🇲' },
  '268': { name: 'Georgia', capital: 'Tbilisi', flag: '🇬🇪' },
  '276': { name: 'Germany', capital: 'Berlin', flag: '🇩🇪' },
  '288': { name: 'Ghana', capital: 'Accra', flag: '🇬🇭' },
  '300': { name: 'Greece', capital: 'Athens', flag: '🇬🇷' },
  '304': { name: 'Greenland', capital: 'Nuuk', flag: '🇬🇱' },
  '320': { name: 'Guatemala', capital: 'Guatemala City', flag: '🇬🇹' },
  '324': { name: 'Guinea', capital: 'Conakry', flag: '🇬🇳' },
  '624': { name: 'Guinea-Bissau', capital: 'Bissau', flag: '🇬🇼' },
  '328': { name: 'Guyana', capital: 'Georgetown', flag: '🇬🇾' },
  '332': { name: 'Haiti', capital: 'Port-au-Prince', flag: '🇭🇹' },
  '340': { name: 'Honduras', capital: 'Tegucigalpa', flag: '🇭🇳' },
  '348': { name: 'Hungary', capital: 'Budapest', flag: '🇭🇺' },
  '352': { name: 'Iceland', capital: 'Reykjavik', flag: '🇮🇸' },
  '356': { name: 'India', capital: 'New Delhi', flag: '🇮🇳' },
  '360': { name: 'Indonesia', capital: 'Jakarta', flag: '🇮🇩' },
  '364': { name: 'Iran', capital: 'Tehran', flag: '🇮🇷' },
  '368': { name: 'Iraq', capital: 'Baghdad', flag: '🇮🇶' },
  '372': { name: 'Ireland', capital: 'Dublin', flag: '🇮🇪' },
  '376': { name: 'Israel', capital: 'Jerusalem', flag: '🇮🇱' },
  '380': { name: 'Italy', capital: 'Rome', flag: '🇮🇹' },
  '388': { name: 'Jamaica', capital: 'Kingston', flag: '🇯🇲' },
  '392': { name: 'Japan', capital: 'Tokyo', flag: '🇯🇵' },
  '400': { name: 'Jordan', capital: 'Amman', flag: '🇯🇴' },
  '398': { name: 'Kazakhstan', capital: 'Astana', flag: '🇰🇿' },
  '404': { name: 'Kenya', capital: 'Nairobi', flag: '🇰🇪' },
  '410': { name: 'South Korea', capital: 'Seoul', flag: '🇰🇷' },
  '414': { name: 'Kuwait', capital: 'Kuwait City', flag: '🇰🇼' },
  '417': { name: 'Kyrgyzstan', capital: 'Bishkek', flag: '🇰🇬' },
  '418': { name: 'Laos', capital: 'Vientiane', flag: '🇱🇦' },
  '428': { name: 'Latvia', capital: 'Riga', flag: '🇱🇻' },
  '422': { name: 'Lebanon', capital: 'Beirut', flag: '🇱🇧' },
  '426': { name: 'Lesotho', capital: 'Maseru', flag: '🇱🇸' },
  '430': { name: 'Liberia', capital: 'Monrovia', flag: '🇱🇷' },
  '434': { name: 'Libya', capital: 'Tripoli', flag: '🇱🇾' },
  '440': { name: 'Lithuania', capital: 'Vilnius', flag: '🇱🇹' },
  '442': { name: 'Luxembourg', capital: 'Luxembourg', flag: '🇱🇺' },
  '450': { name: 'Madagascar', capital: 'Antananarivo', flag: '🇲🇬' },
  '454': { name: 'Malawi', capital: 'Lilongwe', flag: '🇲🇼' },
  '458': { name: 'Malaysia', capital: 'Kuala Lumpur', flag: '🇲🇾' },
  '466': { name: 'Mali', capital: 'Bamako', flag: '🇲🇱' },
  '478': { name: 'Mauritania', capital: 'Nouakchott', flag: '🇲🇷' },
  '484': { name: 'Mexico', capital: 'Mexico City', flag: '🇲🇽' },
  '498': { name: 'Moldova', capital: 'Chișinău', flag: '🇲🇩' },
  '496': { name: 'Mongolia', capital: 'Ulaanbaatar', flag: '🇲🇳' },
  '499': { name: 'Montenegro', capital: 'Podgorica', flag: '🇲🇪' },
  '504': { name: 'Morocco', capital: 'Rabat', flag: '🇲🇦' },
  '508': { name: 'Mozambique', capital: 'Maputo', flag: '🇲🇿' },
  '104': { name: 'Myanmar', capital: 'Naypyidaw', flag: '🇲🇲' },
  '516': { name: 'Namibia', capital: 'Windhoek', flag: '🇳🇦' },
  '524': { name: 'Nepal', capital: 'Kathmandu', flag: '🇳🇵' },
  '528': { name: 'Netherlands', capital: 'Amsterdam', flag: '🇳🇱' },
  '540': { name: 'New Caledonia', capital: 'Nouméa', flag: '🇳🇨' },
  '554': { name: 'New Zealand', capital: 'Wellington', flag: '🇳🇿' },
  '558': { name: 'Nicaragua', capital: 'Managua', flag: '🇳🇮' },
  '562': { name: 'Niger', capital: 'Niamey', flag: '🇳🇪' },
  '566': { name: 'Nigeria', capital: 'Abuja', flag: '🇳🇬' },
  '408': { name: 'North Korea', capital: 'Pyongyang', flag: '🇰🇵' },
  '807': { name: 'North Macedonia', capital: 'Skopje', flag: '🇲🇰' },
  '578': { name: 'Norway', capital: 'Oslo', flag: '🇳🇴' },
  '512': { name: 'Oman', capital: 'Muscat', flag: '🇴🇲' },
  '586': { name: 'Pakistan', capital: 'Islamabad', flag: '🇵🇰' },
  '275': { name: 'Palestine', capital: 'Ramallah', flag: '🇵🇸' },
  '591': { name: 'Panama', capital: 'Panama City', flag: '🇵🇦' },
  '598': { name: 'Papua New Guinea', capital: 'Port Moresby', flag: '🇵🇬' },
  '600': { name: 'Paraguay', capital: 'Asunción', flag: '🇵🇾' },
  '604': { name: 'Peru', capital: 'Lima', flag: '🇵🇪' },
  '608': { name: 'Philippines', capital: 'Manila', flag: '🇵🇭' },
  '616': { name: 'Poland', capital: 'Warsaw', flag: '🇵🇱' },
  '620': { name: 'Portugal', capital: 'Lisbon', flag: '🇵🇹' },
  '630': { name: 'Puerto Rico', capital: 'San Juan', flag: '🇵🇷' },
  '634': { name: 'Qatar', capital: 'Doha', flag: '🇶🇦' },
  '642': { name: 'Romania', capital: 'Bucharest', flag: '🇷🇴' },
  '643': { name: 'Russia', capital: 'Moscow', flag: '🇷🇺' },
  '646': { name: 'Rwanda', capital: 'Kigali', flag: '🇷🇼' },
  '682': { name: 'Saudi Arabia', capital: 'Riyadh', flag: '🇸🇦' },
  '686': { name: 'Senegal', capital: 'Dakar', flag: '🇸🇳' },
  '688': { name: 'Serbia', capital: 'Belgrade', flag: '🇷🇸' },
  '694': { name: 'Sierra Leone', capital: 'Freetown', flag: '🇸🇱' },
  '702': { name: 'Singapore', capital: 'Singapore', flag: '🇸🇬' },
  '703': { name: 'Slovakia', capital: 'Bratislava', flag: '🇸🇰' },
  '705': { name: 'Slovenia', capital: 'Ljubljana', flag: '🇸🇮' },
  '90':  { name: 'Solomon Islands', capital: 'Honiara', flag: '🇸🇧' },
  '706': { name: 'Somalia', capital: 'Mogadishu', flag: '🇸🇴' },
  '710': { name: 'South Africa', capital: 'Pretoria', flag: '🇿🇦' },
  '728': { name: 'South Sudan', capital: 'Juba', flag: '🇸🇸' },
  '724': { name: 'Spain', capital: 'Madrid', flag: '🇪🇸' },
  '144': { name: 'Sri Lanka', capital: 'Colombo', flag: '🇱🇰' },
  '729': { name: 'Sudan', capital: 'Khartoum', flag: '🇸🇩' },
  '740': { name: 'Suriname', capital: 'Paramaribo', flag: '🇸🇷' },
  '748': { name: 'Eswatini', capital: 'Mbabane', flag: '🇸🇿' },
  '752': { name: 'Sweden', capital: 'Stockholm', flag: '🇸🇪' },
  '756': { name: 'Switzerland', capital: 'Bern', flag: '🇨🇭' },
  '760': { name: 'Syria', capital: 'Damascus', flag: '🇸🇾' },
  '158': { name: 'Taiwan', capital: 'Taipei', flag: '🇹🇼' },
  '762': { name: 'Tajikistan', capital: 'Dushanbe', flag: '🇹🇯' },
  '834': { name: 'Tanzania', capital: 'Dodoma', flag: '🇹🇿' },
  '764': { name: 'Thailand', capital: 'Bangkok', flag: '🇹🇭' },
  '626': { name: 'Timor-Leste', capital: 'Dili', flag: '🇹🇱' },
  '768': { name: 'Togo', capital: 'Lomé', flag: '🇹🇬' },
  '780': { name: 'Trinidad and Tobago', capital: 'Port of Spain', flag: '🇹🇹' },
  '788': { name: 'Tunisia', capital: 'Tunis', flag: '🇹🇳' },
  '792': { name: 'Turkey', capital: 'Ankara', flag: '🇹🇷' },
  '795': { name: 'Turkmenistan', capital: 'Ashgabat', flag: '🇹🇲' },
  '800': { name: 'Uganda', capital: 'Kampala', flag: '🇺🇬' },
  '804': { name: 'Ukraine', capital: 'Kyiv', flag: '🇺🇦' },
  '784': { name: 'United Arab Emirates', capital: 'Abu Dhabi', flag: '🇦🇪' },
  '826': { name: 'United Kingdom', capital: 'London', flag: '🇬🇧' },
  '840': { name: 'United States', capital: 'Washington D.C.', flag: '🇺🇸' },
  '858': { name: 'Uruguay', capital: 'Montevideo', flag: '🇺🇾' },
  '860': { name: 'Uzbekistan', capital: 'Tashkent', flag: '🇺🇿' },
  '548': { name: 'Vanuatu', capital: 'Port Vila', flag: '🇻🇺' },
  '862': { name: 'Venezuela', capital: 'Caracas', flag: '🇻🇪' },
  '704': { name: 'Vietnam', capital: 'Hanoi', flag: '🇻🇳' },
  '732': { name: 'Western Sahara', capital: 'Laayoune', flag: '🇪🇭' },
  '887': { name: 'Yemen', capital: "Sana'a", flag: '🇾🇪' },
  '894': { name: 'Zambia', capital: 'Lusaka', flag: '🇿🇲' },
  '716': { name: 'Zimbabwe', capital: 'Harare', flag: '🇿🇼' },
  // Territories & smaller
  '10':  { name: 'Antarctica', capital: 'Research Stations', flag: '🇦🇶' },
  '260': { name: 'French Southern Territories', capital: 'Port-aux-Français', flag: '🇹🇫' },
  '570': { name: 'Niue', capital: 'Alofi', flag: '🇳🇺' },
  '574': { name: 'Norfolk Island', capital: 'Kingston', flag: '🇳🇫' },
  '580': { name: 'Northern Mariana Islands', capital: 'Saipan', flag: '🇲🇵' },
  '036': { name: 'Australia', capital: 'Canberra', flag: '🇦🇺' },
  '-99': { name: 'N. Cyprus', capital: 'North Nicosia', flag: '🇨🇾' },
  '900': { name: 'Kosovo', capital: 'Pristina', flag: '🇽🇰' },
};

/**
 * Major city coordinates for animated dots on the map
 */
export const CITY_DOTS = [
  { lon: -74.0, lat: 40.7, label: 'New York' },
  { lon: -0.1,  lat: 51.5, label: 'London' },
  { lon: 77.2,  lat: 28.6, label: 'New Delhi' },
  { lon: 139.7, lat: 35.7, label: 'Tokyo' },
  { lon: 116.4, lat: 39.9, label: 'Beijing' },
  { lon: 2.35,  lat: 48.8, label: 'Paris' },
  { lon: 37.6,  lat: 55.8, label: 'Moscow' },
  { lon: -43.2, lat: -22.9, label: 'Rio de Janeiro' },
  { lon: 151.2, lat: -33.9, label: 'Sydney' },
  { lon: -99.1, lat: 19.4, label: 'Mexico City' },
  { lon: 31.2,  lat: 30.0, label: 'Cairo' },
  { lon: 28.9,  lat: 41.0, label: 'Istanbul' },
  { lon: 55.3,  lat: 25.3, label: 'Dubai' },
  { lon: 126.9, lat: 37.6, label: 'Seoul' },
  { lon: 100.5, lat: 13.7, label: 'Bangkok' },
  { lon: 106.8, lat: -6.2,  label: 'Jakarta' },
  { lon: 36.8,  lat: -1.3,  label: 'Nairobi' },
  { lon: -46.6, lat: -23.5, label: 'São Paulo' },
  { lon: 18.4,  lat: -34.0, label: 'Cape Town' },
  { lon: 103.8, lat: 1.35,  label: 'Singapore' },
  { lon: -122.4, lat: 37.8, label: 'San Francisco' },
  { lon: 13.4,  lat: 52.5, label: 'Berlin' },
  { lon: 46.7,  lat: 24.7, label: 'Riyadh' },
  { lon: 67.0,  lat: 24.9, label: 'Karachi' },
  { lon: 72.8,  lat: 19.1, label: 'Mumbai' },
];
