import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, CheckCircle2, Clock, Gauge, Play, TrendingUp, X } from 'lucide-react';
import { api } from '../api';
import Sidebar from '../components/worldpulse/Sidebar';
import LockedNavToast from '../components/worldpulse/LockedNavToast';
import { normalizeDashboardData } from '../lib/dashboardAdapter';

function scenarioFromShift(shift) {
  const subject = shift.headline || shift.category || 'this signal';
  return `What if ${subject.toLowerCase()} escalates?`;
}

function ImpactCards({ result }) {
  const areas = result?.impact_areas || [];
  return (
    <section className="sim-impact-grid">
      {areas.map((item) => (
        <div className="wp-card sim-impact-card" key={item.area}>
          <div className="sim-impact-head">
            <span>{item.area}</span>
            <b>{item.score}</b>
          </div>
          <small>{item.direction}</small>
          <p>{item.explanation}</p>
        </div>
      ))}
    </section>
  );
}

export default function SimulatorPage() {
  const navigate = useNavigate();
  const [scenario, setScenario] = useState('');
  const [assumptions, setAssumptions] = useState({ time_horizon: '30d', severity: 'medium', market_reaction: 'medium' });
  const [dashboard, setDashboard] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [contextLoading, setContextLoading] = useState(true);
  const [contextError, setContextError] = useState('');
  const [error, setError] = useState('');
  const [lockedToast, setLockedToast] = useState('');

  const loadContext = useCallback(async () => {
    setContextLoading(true);
    setContextError('');
    try {
      const response = await api.getCachedDashboard();
      setDashboard(response);
    } catch (err) {
      setDashboard(null);
      setContextError((err?.message || 'Unable to load live scenario seeds.').replace(/^\d+:\s*/, '').slice(0, 180));
    } finally {
      setContextLoading(false);
    }
  }, []);

  useEffect(() => {
    loadContext();
  }, [loadContext]);

  const normalized = useMemo(() => normalizeDashboardData({ dashboard, preferences: null, alerts: null, user: null }), [dashboard]);
  const scenarioSeeds = useMemo(() => normalized.topShifts.slice(0, 4), [normalized.topShifts]);

  const run = async () => {
    setLoading(true);
    setError('');
    setResult(null);
    try {
      const response = await api.simulate({ scenario, assumptions });
      setResult(response.result);
    } catch (err) {
      setError((err?.message || 'Scenario failed.').replace(/^\d+:\s*/, '').slice(0, 220));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="world-pulse-page simulator-page">
      <Sidebar
        preferences={{ hasPreferences: Boolean(normalized.preferences?.topics?.length), topics: normalized.preferences?.topics || [], regions: normalized.preferences?.regions || [], entities: [] }}
        activeItem="simulator"
        onHome={() => navigate('/dashboard')}
        onOrbit={() => navigate('/orbit')}
        onStories={() => navigate('/stories')}
        onMap={() => navigate('/map')}
        onSimulator={() => {}}
        onLocked={setLockedToast}
        onWatchlist={() => navigate('/watchlist')}
        onAlerts={() => navigate('/alerts')}
        onSetFocus={() => navigate('/onboarding')}
        onSettings={() => navigate('/settings')}
      />
      <main className="world-pulse-main simulator-main">
        <header className="orbit-header ni-screen-header">
          <div>
            <h1>Scenario Simulator</h1>
            <p>Model possible futures using recent events, relationships, geo metadata, and AI reasoning.</p>
          </div>
          <button className="wp-icon-btn" onClick={() => setLockedToast('Scenario outputs are generated by the backend AI simulator.')}><Gauge size={16} /> How it works</button>
        </header>

        <section className="simulator-layout">
          <div className="simulator-left">
            <div className="wp-card scenario-input-panel">
              <div className="wp-section-head"><span>What scenario do you want to explore?</span></div>
              <textarea value={scenario} onChange={(event) => setScenario(event.target.value)} placeholder="What if..." />
              <div className="preset-row live-scenario-seeds">
                {contextLoading && <span>Loading live scenario seeds...</span>}
                {!contextLoading && contextError && <span>{contextError}</span>}
                {!contextLoading && scenarioSeeds.map((shift) => (
                  <button key={shift.id} onClick={() => setScenario(scenarioFromShift(shift))}>
                    {shift.headline}
                  </button>
                ))}
              </div>
              <button className="orbit-story-button run-scenario" onClick={run} disabled={loading || scenario.trim().length < 12}>
                <Play size={16} /> {loading ? 'Running...' : 'Run Scenario'}
              </button>
            </div>

            {result && <ImpactCards result={result} />}

            <div className="wp-card sim-chain-panel" style={{ minHeight: '300px', position: 'relative' }}>
              <div className="wp-section-head"><span>Interactive Impact Chain</span></div>
              {result?.chain_reaction?.length ? (
                <div className="sim-chain-interactive" style={{ display: 'flex', gap: '20px', overflowX: 'auto', padding: '20px' }}>
                  {result.chain_reaction.map((item, i) => (
                    <div 
                      className="sim-chain-node" 
                      key={item.step}
                      style={{ 
                        flexShrink: 0, width: '220px', padding: '16px', 
                        background: `rgba(139, 92, 246, ${0.05 + (i * 0.05)})`,
                        border: '1px solid rgba(139, 92, 246, 0.2)',
                        borderRadius: '12px', cursor: 'grab',
                        transition: 'transform 0.2s',
                        transform: `translateY(${i % 2 === 0 ? '0' : '20px'})`
                      }}
                      onMouseEnter={(e) => e.currentTarget.style.transform = `translateY(${i % 2 === 0 ? '-5px' : '15px'}) scale(1.05)`}
                      onMouseLeave={(e) => e.currentTarget.style.transform = `translateY(${i % 2 === 0 ? '0' : '20px'}) scale(1)`}
                    >
                      <i style={{ 
                        display: 'inline-flex', width: 24, height: 24, 
                        background: '#8b5cf6', color: '#fff', borderRadius: '50%',
                        alignItems: 'center', justifyContent: 'center', marginBottom: 12 
                      }}>{item.step}</i>
                      <b style={{ display: 'block', marginBottom: 8, color: '#c4b5fd' }}>{item.title}</b>
                      <span style={{ fontSize: 12, color: '#94a3b8' }}>{item.description}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="empty-copy">Run a scenario to generate an interactive chain reaction.</p>
              )}
            </div>

            <div className="wp-card sim-outcomes-panel">
              <div className="wp-section-head"><span>Possible Outcomes</span></div>
              <div className="sim-outcomes">
                {result?.possible_outcomes?.map((item) => (
                  <div className="sim-outcome" key={item.label}>
                    <b>{item.probability}%</b>
                    <span>{item.label}</span>
                    <p>{item.description}</p>
                  </div>
                ))}
                {!result?.possible_outcomes?.length && <p className="empty-copy">Outcome probabilities come from the AI simulator response.</p>}
              </div>
            </div>
          </div>

          <aside className="wp-card simulator-side">
            <div className="wp-section-head"><span>Scenario Summary</span></div>
            {loading && <div className="wp-loading"><span /></div>}
            {error && <div className="wp-error"><b>Scenario unavailable</b><span>{error}</span><button onClick={() => setError('')}><X size={14} /></button></div>}
            {!loading && !error && !result && (
              <div className="orbit-empty">
                <h2>Awaiting scenario input.</h2>
                <p>The result panel stays empty until the backend simulator returns scenario JSON.</p>
              </div>
            )}
            {result && (
              <div className="scenario-result">
                <div className="scenario-score">
                  <div><b>{result.impact_score}</b><span>Overall Impact</span></div>
                  <div><b>{result.confidence}</b><span>Confidence</span></div>
                </div>
                <p>{result.summary}</p>
                <p className="scenario-disclaimer">{result.disclaimer}</p>
                <section>
                  <h3>Key Assumptions</h3>
                  <div className="assumption-list">
                    <div><AlertTriangle size={15} /><span>Severity</span><b>{assumptions.severity}</b></div>
                    <div><TrendingUp size={15} /><span>Market reaction</span><b>{assumptions.market_reaction}</b></div>
                    <div><Clock size={15} /><span>Time horizon</span><b>{assumptions.time_horizon}</b></div>
                  </div>
                </section>
                <section>
                  <h3>Recommended Actions</h3>
                  {result.recommended_actions?.length ? result.recommended_actions.map((item) => (
                    <p key={item}><CheckCircle2 size={14} /> {item}</p>
                  )) : <p className="empty-copy">No recommended actions returned by the simulator.</p>}
                </section>
              </div>
            )}
            <section className="orbit-controls sim-controls" style={{ display: 'flex', flexDirection: 'column', gap: '16px', padding: '16px' }}>
              <div className="interactive-slider-group">
                <label style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                  <span>Time Horizon</span> <b>{assumptions.time_horizon}</b>
                </label>
                <input 
                  type="range" min="0" max="2" step="1" 
                  value={assumptions.time_horizon === '7d' ? 0 : assumptions.time_horizon === '30d' ? 1 : 2}
                  onChange={(e) => setAssumptions({...assumptions, time_horizon: ['7d', '30d', '90d'][e.target.value]})}
                  style={{ width: '100%', cursor: 'ew-resize' }}
                />
              </div>
              <div className="interactive-slider-group">
                <label style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                  <span>Severity</span> <b>{assumptions.severity}</b>
                </label>
                <input 
                  type="range" min="0" max="2" step="1" 
                  value={assumptions.severity === 'low' ? 0 : assumptions.severity === 'medium' ? 1 : 2}
                  onChange={(e) => setAssumptions({...assumptions, severity: ['low', 'medium', 'high'][e.target.value]})}
                  style={{ width: '100%', cursor: 'ew-resize' }}
                />
              </div>
              <div className="interactive-slider-group">
                <label style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                  <span>Market Reaction</span> <b>{assumptions.market_reaction}</b>
                </label>
                <input 
                  type="range" min="0" max="2" step="1" 
                  value={assumptions.market_reaction === 'low' ? 0 : assumptions.market_reaction === 'medium' ? 1 : 2}
                  onChange={(e) => setAssumptions({...assumptions, market_reaction: ['low', 'medium', 'high'][e.target.value]})}
                  style={{ width: '100%', cursor: 'ew-resize' }}
                />
              </div>
            </section>
          </aside>
        </section>
      </main>
      <LockedNavToast message={lockedToast} />
    </div>
  );
}
