import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, CheckCircle2, Clock, Gauge, Play, TrendingUp, X } from 'lucide-react';
import { api } from '../api';
import Sidebar from '../components/worldpulse/Sidebar';
import LockedNavToast from '../components/worldpulse/LockedNavToast';
import { normalizeDashboardData } from '../lib/dashboardAdapter';

function scenarioFromShift(shift) {
  const subject = shift.headline || shift.category || 'this signal';
  return `What if ${subject.toLowerCase()} escalates over the next 30 days?`;
}

function ImpactCards({ result }) {
  const areas = result?.impact_areas || [];
  return (
    <section className="sim-impact-grid">
      {areas.map((item) => (
        <div className="wp-card sim-impact-card" key={item.area}>
          <span>{item.area}</span>
          <b>{item.score}</b>
          <small>{item.direction}</small>
          <p>{item.explanation}</p>
        </div>
      ))}
    </section>
  );
}

export default function SimulatorPage() {
  const navigate = useNavigate();
  const [scenario, setScenario] = useState('');
  const [assumptions, setAssumptions] = useState({ time_horizon: '30d', severity: 'medium', market_reaction: 'medium' });
  const [dashboard, setDashboard] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [contextLoading, setContextLoading] = useState(true);
  const [error, setError] = useState('');
  const [lockedToast, setLockedToast] = useState('');

  const loadContext = useCallback(async () => {
    setContextLoading(true);
    try {
      const response = await api.getCachedDashboard();
      setDashboard(response);
    } catch {
      setDashboard(null);
    } finally {
      setContextLoading(false);
    }
  }, []);

  useEffect(() => {
    loadContext();
  }, [loadContext]);

  const normalized = useMemo(() => normalizeDashboardData({ dashboard, preferences: null, alerts: null, user: null }), [dashboard]);
  const scenarioSeeds = useMemo(() => normalized.topShifts.slice(0, 4), [normalized.topShifts]);

  const run = async () => {
    setLoading(true);
    setError('');
    setResult(null);
    try {
      const response = await api.simulate({ scenario, assumptions });
      setResult(response.result);
    } catch (err) {
      setError((err?.message || 'Scenario failed.').replace(/^\d+:\s*/, '').slice(0, 220));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="world-pulse-page simulator-page">
      <Sidebar
        preferences={{ hasPreferences: Boolean(normalized.preferences?.topics?.length), topics: normalized.preferences?.topics || [], regions: normalized.preferences?.regions || [], entities: [] }}
        activeItem="simulator"
        onHome={() => navigate('/dashboard')}
        onOrbit={() => navigate('/orbit')}
        onMap={() => navigate('/map')}
        onSimulator={() => {}}
        onLocked={setLockedToast}
        onWatchlist={() => navigate('/watchlist')}
        onAlerts={() => navigate('/alerts')}
        onSetFocus={() => navigate('/onboarding')}
        onSettings={() => navigate('/settings')}
      />
      <main className="world-pulse-main simulator-main">
        <header className="orbit-header ni-screen-header">
          <div>
            <h1>Scenario Simulator</h1>
            <p>Model possible futures using recent events, relationships, geo metadata, and AI reasoning.</p>
          </div>
          <button className="wp-icon-btn" onClick={() => setLockedToast('Scenario outputs are generated by the backend AI simulator.')}><Gauge size={16} /> How it works</button>
        </header>

        <section className="simulator-layout">
          <div className="simulator-left">
            <div className="wp-card scenario-input-panel">
              <div className="wp-section-head"><span>What scenario do you want to explore?</span></div>
              <textarea value={scenario} onChange={(event) => setScenario(event.target.value)} placeholder="What if..." />
              <div className="preset-row live-scenario-seeds">
                {contextLoading && <span>Loading live scenario seeds...</span>}
                {!contextLoading && scenarioSeeds.map((shift) => (
                  <button key={shift.id} onClick={() => setScenario(scenarioFromShift(shift))}>
                    {shift.headline}
                  </button>
                ))}
              </div>
              <button className="orbit-story-button run-scenario" onClick={run} disabled={loading || scenario.trim().length < 12}>
                <Play size={16} /> {loading ? 'Running...' : 'Run Scenario'}
              </button>
            </div>

            {result && <ImpactCards result={result} />}

            <div className="wp-card sim-chain-panel">
              <div className="wp-section-head"><span>How The Impact Might Unfold</span></div>
              {result?.chain_reaction?.length ? (
                <div className="sim-chain">
                  {result.chain_reaction.map((item) => (
                    <div className="sim-chain-step" key={item.step}>
                      <i>{item.step}</i>
                      <b>{item.title}</b>
                      <span>{item.description}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="empty-copy">Run a scenario to generate a backend chain reaction.</p>
              )}
            </div>

            <div className="wp-card sim-outcomes-panel">
              <div className="wp-section-head"><span>Possible Outcomes</span></div>
              <div className="sim-outcomes">
                {result?.possible_outcomes?.map((item) => (
                  <div className="sim-outcome" key={item.label}>
                    <b>{item.probability}%</b>
                    <span>{item.label}</span>
                    <p>{item.description}</p>
                  </div>
                ))}
                {!result?.possible_outcomes?.length && <p className="empty-copy">Outcome probabilities come from the AI simulator response.</p>}
              </div>
            </div>
          </div>

          <aside className="wp-card simulator-side">
            <div className="wp-section-head"><span>Scenario Summary</span></div>
            {loading && <div className="wp-loading"><span /></div>}
            {error && <div className="wp-error"><b>Scenario unavailable</b><span>{error}</span><button onClick={() => setError('')}><X size={14} /></button></div>}
            {!loading && !error && !result && (
              <div className="orbit-empty">
                <h2>Ready when you are.</h2>
                <p>The result panel stays empty until the backend simulator returns scenario JSON.</p>
              </div>
            )}
            {result && (
              <div className="scenario-result">
                <div className="scenario-score"><b>{result.impact_score}</b><span>overall impact</span><b>{result.confidence}</b><span>confidence</span></div>
                <p>{result.summary}</p>
                <p className="scenario-disclaimer">{result.disclaimer}</p>
                <section>
                  <h3>Key Assumptions</h3>
                  <div className="assumption-list">
                    <div><AlertTriangle size={15} /><span>Severity</span><b>{assumptions.severity}</b></div>
                    <div><TrendingUp size={15} /><span>Market reaction</span><b>{assumptions.market_reaction}</b></div>
                    <div><Clock size={15} /><span>Time horizon</span><b>{assumptions.time_horizon}</b></div>
                  </div>
                </section>
                <section>
                  <h3>Recommended Actions</h3>
                  {result.recommended_actions?.length ? result.recommended_actions.map((item) => (
                    <p key={item}><CheckCircle2 size={14} /> {item}</p>
                  )) : <p className="empty-copy">No actions returned.</p>}
                </section>
              </div>
            )}
            <section className="orbit-controls sim-controls">
              <label>Time<select value={assumptions.time_horizon} onChange={(event) => setAssumptions({ ...assumptions, time_horizon: event.target.value })}><option value="7d">7d</option><option value="30d">30d</option><option value="90d">90d</option></select></label>
              <label>Severity<select value={assumptions.severity} onChange={(event) => setAssumptions({ ...assumptions, severity: event.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>
              <label>Markets<select value={assumptions.market_reaction} onChange={(event) => setAssumptions({ ...assumptions, market_reaction: event.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>
            </section>
          </aside>
        </section>
      </main>
      <LockedNavToast message={lockedToast} />
    </div>
  );
}
